[package]
name = "bitboard"
version = "0.1.0"
authors = ["Julius McPherson <julius.mcpherson219@mod.gov.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.10.0"